# config.py

WORD_SIMILARITY_THRESHOLD = 0.7
SEGMENT_SCORE_THRESHOLD = 0.5

LEVENSHTEIN_WEIGHT = 0.7
LENGTH_PENALTY_WEIGHT = 0.3

TRACKING_WINDOW_SIZE = 40
BACKWARD_MARGIN = 15

MIN_SEGMENT_WORDS = 5
MAX_SEGMENT_WORDS = 25
SEGMENT_STRIDE = 3

CONFIDENCE_THRESHOLD = 0.3
MAX_LOW_CONFIDENCE_CHUNKS = 3

SEQUENCE_SKIP_MIN_WORDS = 12
SEQUENCE_BACKWARDS_TOLERANCE = 3
